# Generated by Django 3.1.5 on 2021-01-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rain',
            options={'verbose_name_plural': 'rain'},
        ),
    ]
