# Generated by Django 3.1.5 on 2021-01-11 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_auto_20210111_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rain',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
